### ISSUE TITLE
How to install to use with faustgen~ for Win64?

### ISSUE THREAD

**Issue by nesdnuma** [rmichon/mi_faust#1]
Hello,

I am trying to test the mass-interaction lib with faustgen~ but I have an issue with faustgen~ itself: where am I supposed to copy the lib and are the Faust regular libraries installed with faustgen~ or am I supposed to install another Faust program beforehand? In this case, which one?

Thank you!

**Comment by rmichon** [comment]
Hello, that's a good question. I'm personally on Linux so I don't really use faustgen. That would be a question for @sletz. The latest version of faustgen should be compiled with a recent version of the Faust lib but proably not the latest version of mi_faust.

**Comment by sletz** [comment]
We plan to publish a Faust binary release next week, with a Windows faustgen~ version that contains the latest version of  mi.lib (that is : https://github.com/grame-cncm/faustlibraries/blob/master/mi.lib right @rmichon ?)

**Comment by nesdnuma** [comment]
That would be great. So all libraries should always be included in faustgen and there's no way to add libraries in a folder somewhere?

**Comment by sletz** [comment]
All standard libraries are distributed with the faustgen external, and you can always add other ones using the `-I /path/to/libraries` syntax in the **compileoptions** message of faustgen.

**Comment by rmichon** [comment]
> We plan to publish a Faust binary release next week, with a Windows faustgen~ version that contains the latest version of mi.lib (that is : https://github.com/grame-cncm/faustlibraries/blob/master/mi.lib right @rmichon ?)

Yes

**Comment by nesdnuma** [comment]
Great to know it's possible to add a lib using the compileoptions in faustgen~!
